version: "2"

run:
  allow-parallel-runners: true
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: vendor

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      # A list of prefixes, which, if set, checks import paths with the given prefixes are grouped after 3rd-party packages.
      local-prefixes:
        - github.com/seaweedfs/seaweedfs

issues:
  max-same-issues: 50 # Maximum count of issues with the same text. Set to 0 to disable. Default: 3

linters:
  default: all

  disable:
    - depguard # we have no denied packages
    - exhaustruct # we do not always need to init all struct fields
    - godot # useless check for dot in the end of a comment
    - godox # it is ok to have todos
    - nilnil # it is ok to return nil, nil
    - noinlineerr # we love inline error handling, it simplifies code reading
    - testpackage # it is ok not to use *_test packages for tests
    - varnamelen # too noisy, requires manual fix, does not affect potential bugs
    - wrapcheck # many FPs: a lot of wrappings are made upper then the check fails
    - wsl_v5 # too noisy, requires manual fix, does not affect potential bugs
    - wsl # [deprecated]
    - gomoddirectives # override some libs versions to avoid dependency conflicts
    - gochecknoglobals # a lot of stuff is implemented using global vars
    - funcorder # no reorder exported (first capital letter) and internal methods
    - tagliatelle
    - canonicalheader

  settings:
    cyclop:
      max-complexity: 30 # The maximal code complexity to report. Default: 10

    embeddedstructfieldcheck:
      forbid-mutex: true # Checks that sync.Mutex and sync.RWMutex are not used as embedded fields. Default: false

    errcheck:
      check-type-assertions: true # Report about not checking of errors in type assertions: `a := b.(MyStruct)`. Default: false

    funlen:
      lines: 180 # Checks the number of lines in a function. Default: 60
      statements: 80 # Checks the number of statements in a function. Default: 40

    gocognit:
      min-complexity: 40 # Minimal code complexity to report. # Default: 30 (but we recommend 10-20)

    gocritic:
      settings:
        captLocal:
          paramsOnly: false # Whether to restrict checker to params only. Default: true
        underef:
          skipRecvDeref: false # Whether to skip (*x).method() calls where x is a pointer receiver. # Default: true

    govet:
      enable-all: true
      disable:
        - fieldalignment # disable rearrange fields in structures

    reassign:
      patterns: # Patterns for global variable names that are checked for reassignment. # Default: ["EOF", "Err.*"]
        - ".*"

  # Defines a set of rules to ignore issues. It does not skip the analysis, and so does not ignore "typecheck" errors.
  exclusions:
    generated: lax # sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc. Default: strict
    warn-unused: true # Log a warning if an exclusion rule is unused. Default: false
    presets: # Predefined exclusion rules. Default: []
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    paths:
      - "vendor"
    rules:
      - linters:
          - revive
        text: "don't use an underscore in package name"
      - linters:
          - govet
        text: "shadow: declaration of \"err\" shadows declaration" # skip err shadowing (as it is a common pattern in Go projects)
      - path: '(.+)_test\.go'
        linters:
          - dupl # tests can have dupl issues by design
      - linters:
          - err113
        text: "do not define dynamic errors, use wrapped static errors instead"
      - linters:
          - revive
        text: "^exported: type name will be used as.*"
